import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useSelector } from "react-redux";
import { wrapper } from "../../../app/store";
import API_CONFIG from "../../../common/constant";
import { formatCategory, getData } from "../../../common/helpers";
import { getCategory } from "../../../features/book/book-actions";

export default function CategoryPage() {
  const { query } = useRouter();
  const { category } = useSelector((state) => state.book);

  return (
    <>
      <Head>
        <title>Daftar Buku {formatCategory(query.category)} | YASLAB</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="w-full pt-14 text-slate-700 dark:text-slate-400">
        <h2 className="mt-10 mb-14 pt-14 text-center text-5xl font-bold capitalize dark:text-slate-200">
          Daftar Buku {formatCategory(query.category)}
        </h2>
        {category.map((book) => (
          <div key={book.id}>
            <Link href={`/books/${query.category}/${book.id}`}>
              <a>{book.info.title}</a>
            </Link>
          </div>
        ))}
      </div>
    </>
  );
}

export async function getStaticPaths() {
  const categories = await getData(API_CONFIG.GET_CATEGORIES);
  const paths = categories.map(({ category }) => ({
    params: { category },
  }));

  return { paths, fallback: false };
}

export const getStaticProps = wrapper.getStaticProps(
  (store) =>
    async ({ params: { category } }) => {
      await store.dispatch(getCategory(category));
    }
);
