import Head from 'next/head';
import { PageWrapper } from '../common/components';

export default function HomePage() {
  return (
    <>
      <Head>
        <title>YASLAB</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <PageWrapper>
        <h1>YASLAB</h1>
      </PageWrapper>
    </>
  );
}
