/* eslint-disable @typescript-eslint/no-explicit-any */
import Head from 'next/head';
import { GetStaticProps, InferGetStaticPropsType, NextPage } from 'next';
import SearchInput from '@/common/components/search-input';
import { BackgroundImage, PageWrapper } from '@/common/components';
import { Categories } from '@/common/types/index.model';
import { getData } from '@/common/helpers';
import API_CONFIG from '@/common/constant';
import { useAppDispatch, useAppSelector } from '@/app/hooks';
import { setCategories } from '@/features/book/books-slice';
import { useEffect } from 'react';

const HomePage: NextPage<InferGetStaticPropsType<typeof getStaticProps>> = ({
  categories,
}: any) => {
  const dispatch = useAppDispatch();
  const { categories: categoriesBook } = useAppSelector((state) => state.books);

  useEffect(() => {
    if (categoriesBook.length === 0) {
      dispatch(setCategories(categories));
    }
  }, [categories, categoriesBook, dispatch]);

  return (
    <>
      <Head>
        <title>Maktaba YARSI - Yarsi Digital Islamic Library</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <PageWrapper>
        <h1 className="mt-20 text-center font-extrabold text-dark-100 dark:text-light-100 lg:text-7xl">
          YARSI Digital Islamic Library
        </h1>
        <p className="mx-auto mt-8 text-center text-lg lg:w-8/12">
          Sebuah perpustakaan islam digital berbahasa Indonesia yang memungkinkan pengguna untuk
          mencari topik atau permasalah berdasarkan kata kunci seperti{' '}
          <span className="highlight">iman</span>, <span className="highlight">sabar</span>,{' '}
          <span className="highlight">shalat</span> dan <span className="highlight">riba</span>.
        </p>
        <SearchInput />
      </PageWrapper>
      <BackgroundImage />
    </>
  );
};

export default HomePage;

export const getStaticProps: GetStaticProps = async () => {
  const { categories }: { categories: Categories } = await getData(API_CONFIG.GET_CATEGORIES);
  return { props: { categories }, revalidate: 60 };
};
