import Head from 'next/head';
import { useEffect, useState } from 'react';
import { paragrafFormatter } from '../utils/helpers';

export default function Home() {
  const [data, setData] = useState([]);

  useEffect(() => {
    const test = async () => {
      const res = await fetch('http://localhost:5000/books');
      const req = await res.json();
      setData(req);
    };
    test();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full m-auto space-y-5">
        {data[0]?.content.map(({ text }, index) => (
          <div
            key={index}
            className="book-page w-1/2 p-4 m-auto text-[#94A3B8] bg-[#0F172A]"
            dangerouslySetInnerHTML={{ __html: paragrafFormatter(text) }}
          />
        ))}
      </main>
    </>
  );
}
