import Head from "next/head";
import { wrapper } from "../app/store";
import { getBooks } from "../features/book";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex w-full pt-14 text-slate-700 duration-150 dark:text-slate-400"></main>
    </>
  );
}

export const getStaticProps = wrapper.getStaticProps((store) => async () => {
  await store.dispatch(getBooks());
});
