import Head from "next/head";
import Link from "next/link";
import { useSelector } from "react-redux";
import { wrapper } from "../../app/store";
import { Breadcrumb, PageWrapper } from "../../common/components";
import { formatCategory } from "../../common/helpers";
import { getCategories } from "../../features/book/book-actions";

export default function CategoriyBooksPage() {
  const { categories } = useSelector((state) => state.book);
  return (
    <>
      <Head>
        <title>Kategori Buku | YASLAB</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <PageWrapper>
        <Breadcrumb routes={[{ title: "categories" }]} />
        <h1 className="mb-10 text-center text-5xl font-bold dark:text-slate-200">
          Kategori Buku Islam
        </h1>
        <div className="mx-auto grid w-max grid-cols-1 gap-10 md:grid-cols-2 lg:grid-cols-3">
          {categories.map(({ category }) => (
            <Link key={category} href={`/books/${category}`}>
              <a className="w-60 rounded-xl border border-green-600 py-3 text-center text-2xl font-medium capitalize duration-300 hover:bg-green-600 hover:text-white dark:border-green-500 hover:dark:bg-green-500 hover:dark:text-slate-900">
                {formatCategory(category)}
              </a>
            </Link>
          ))}
        </div>
      </PageWrapper>
    </>
  );
}

export const getStaticProps = wrapper.getStaticProps((store) => async () => {
  await store.dispatch(getCategories());
});
