import Head from 'next/head';

const SearchPage = () => {
  return (
    <>
      <Head>
        <title>YASLABf</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="pt-14 text-white">F</main>
    </>
  );
};

export default SearchPage;
