import Head from 'next/head';
import { useEffect, useState } from 'react';

export default function Home() {
  const [data, setData] = useState([]);

  useEffect(() => {
    const test = async () => {
      const res = await fetch('http://localhost:5000/books');
      const req = await res.json();
      setData(req);
    };
    test();
  }, []);
  console.log(data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p className="bg-red-600 text-white">{data[0]?.content[5]?.text}</p>
      </main>
    </>
  );
}
